### ISSUE TITLE
28/03/2023 Xác định các mối quan hệ giữa các actor và các usecase

### ISSUE THREAD

**Issue by TrnHunhTnPht** [TrnHunhTnPht/Nhom13-DETAI23-API-DASHBOARD#52]

**Comment by maihaidang2102** [comment]
Mối quan hệ giữa các actor và các usecase : [link](https://docs.google.com/document/d/1gimioAIvK1ItZslSGw7Q2_aP0JaZujZfIkM5raClOjA/edit?usp=sharing)
Done TASK 1

**Comment by maihaidang2102** [comment]
Trong phương pháp phát triển phần mềm hướng đối tượng, các Use Case và Actor là những thành phần cơ bản để mô hình hóa yêu cầu của khách hàng.
Use Case là mô tả các hoạt động và hành vi của hệ thống trong một kịch bản nhất định. Mỗi Use Case có thể liên quan đến nhiều Actor, đại diện cho các thực thể trong và ngoài hệ thống, có liên quan trực tiếp đến Use Case đó.
Actor đại diện cho một vai trò cụ thể mà một người sử dụng hoặc hệ thống khác có thể đóng trong hệ thống. Một Actor có thể liên quan đến nhiều Use Case, đại diện cho các hành động mà Actor đó có thể thực hiện trong hệ thống.
Các mối quan hệ giữa các Actor và Use Case có thể được miêu tả như sau:
Một Actor có thể kích hoạt nhiều Use Case: Điều này có nghĩa là một Actor có thể có nhiều hành động khác nhau trong hệ thống, mỗi hành động đó tương ứng với một Use Case khác nhau.
Nhiều Actor có thể kích hoạt một Use Case: Một Use Case có thể được kích hoạt bởi nhiều Actor khác nhau, tùy thuộc vào các hoạt động và vai trò của các Actor đó trong hệ thống.
Một Actor có thể liên quan đến nhiều Use Case: Một Actor có thể có nhiều hành động khác nhau trong hệ thống, và mỗi hành động đó tương ứng với một Use Case khác nhau.
Một Use Case có thể liên quan đến nhiều Actor: Một Use Case có thể được kích hoạt bởi nhiều Actor khác nhau, tùy thuộc vào các hoạt động và vai trò của các Actor đó trong hệ thống.
Tóm lại, Actor và Use Case là hai thành phần quan trọng trong mô hình hóa yêu cầu của phần mềm, và các mối quan hệ giữa chúng giúp cho nhà phát triển hiểu rõ hơn về cách thức mà hệ thống được sử dụng và tương tác với người dùng.
