### ISSUE TITLE
29/03/2023 Lưu ý khi vẽ use case diagram

### ISSUE THREAD

**Issue by TrnHunhTnPht** [TrnHunhTnPht/Nhom13-DETAI23-API-DASHBOARD#53]

**Comment by maihaidang2102** [comment]
Lưu ý khi vẽ use case diagram : [link](https://docs.google.com/document/d/1j_G2MFi2k3fGchrpmNmyOFDbABW_N2yKyyR8J-1AQ_Y/edit?usp=sharing)
DONE TASK 2

**Comment by maihaidang2102** [comment]
Khi vẽ Use Case Diagram, bạn cần lưu ý một số điểm sau để đảm bảo sự hiểu quả của mô hình:

- Chọn các Use Case phù hợp: Chọn các Use Case mà người dùng cần và sử dụng để hoàn thành các nhiệm vụ trong hệ thống. Tránh chọn quá nhiều Use Case hoặc những Use Case không cần thiết.
- Xác định các Actor: Xác định các Actor và vai trò của họ trong hệ thống. Chú ý đến các Actor chính và phụ, và cân nhắc đến các Actor bên ngoài hệ thống.
- Sắp xếp các Use Case: Sắp xếp các Use Case sao cho chúng liên quan đến nhau và dễ đọc hơn. Bạn có thể sử dụng các mũi tên để chỉ ra mối quan hệ giữa các Use Case.
- Đặt tên cho các Use Case và Actor: Đặt tên cho các Use Case và Actor sao cho nó thể hiện đầy đủ chức năng của chúng. Sử dụng các thuật ngữ phù hợp và tránh sử dụng các từ ngữ mơ hồ hoặc khó hiểu.
- Sử dụng ghi chú (notes) khi cần thiết: Sử dụng ghi chú để giải thích các khía cạnh phức tạp của hệ thống hoặc để cung cấp thông tin bổ sung về các Use Case hoặc Actor.
- Cân nhắc các phân cấp (hierarchy): Nếu hệ thống có các Use Case phức tạp hoặc liên quan đến nhau, bạn có thể sử dụng phân cấp để giảm độ phức tạp của mô hình.
- Lưu ý đến các ràng buộc (constraints): Nếu có các ràng buộc về thời gian, tài nguyên hoặc các yêu cầu khác, bạn cần thể hiện chúng trên Use Case Diagram để tránh những sai lệch về yêu cầu trong quá trình phát triển.
- Sử dụng công cụ hỗ trợ: Sử dụng các công cụ hỗ trợ vẽ sẽ giúp bạn vẽ Use Case Diagram nhanh hơn và chính xác hơn. Nhiều công cụ miễn phí và trả phí có sẵn trên internet để lựa chọn.

Tóm lại, Use Case Diagram là một phần quan trọng của phương pháp phát triển phần mềm hướng đối tượng, giúp người dùng và nhà phát triển hiểu rõ hơn về chức năng và mối quan hệ của hệ thống. B
