### ISSUE TITLE
31/03/2023 Xác định các thuộc tính của class Admin

### ISSUE THREAD

**Issue by TrnHunhTnPht** [TrnHunhTnPht/Nhom13-DETAI23-API-DASHBOARD#56]

**Comment by maihaidang2102** [comment]
Các thuộc tính của class APIManager : [link](https://docs.google.com/document/d/1bAl2R2mRgKDWmjP_gIUDonQWdsQDXmf6oS0UC6qBrVU/edit?usp=sharing)
DONE TASK 4

**Comment by maihaidang2102** [comment]
APIManager là một lớp quản lý API trong hệ thống phần mềm, các thuộc tính có thể bao gồm:

- apiList: Một danh sách các API có sẵn trong hệ thống.
- apiKey: Một chuỗi mã xác thực được sử dụng để truy cập các API.
- apiVersion: Phiên bản của API được sử dụng.
- apiTimeout: Thời gian chờ tối đa để thực hiện các yêu cầu API trước khi hết thời gian chờ.
- apiCache: Một bộ nhớ cache để lưu trữ các kết quả từ các yêu cầu API trước đó.
- apiRateLimit: Giới hạn tốc độ yêu cầu API trong một khoảng thời gian nhất định.

Ngoài ra, APIManager cũng có thể bao gồm các thuộc tính khác như: apiRequestHeader, apiResponseHeader, apiLoggingLevel, apiRetryAttempts, ... tùy thuộc vào yêu cầu của hệ thống và các tính năng được hỗ trợ bởi APIManager.
