### ISSUE TITLE
01/04/2023 Xác định các phương thức của class Admin

### ISSUE THREAD

**Issue by TrnHunhTnPht** [TrnHunhTnPht/Nhom13-DETAI23-API-DASHBOARD#57]

**Comment by maihaidang2102** [comment]
Cách phương thức dự kiến của class APIManager : [link](https://docs.google.com/document/d/1FTuJSWE8d-wxOE0wCuHUcYMGi7Y3NxGuxegEft5UxK0/edit?usp=sharing)
DONE TASK5

**Comment by maihaidang2102** [comment]
Các phương thức của lớp APIManager có thể bao gồm:

- addAPI(): Thêm một API mới vào danh sách các API có sẵn.
- removeAPI(): Xóa một API khỏi danh sách các API có sẵn.
- getAPI(): Truy cập thông tin của một API trong danh sách.
- setAPIKey(): Thiết lập mã xác thực để truy cập các API.
- setApiVersion(): Thiết lập phiên bản của API được sử dụng.
- setApiTimeout(): Thiết lập thời gian chờ tối đa cho các yêu cầu API.
- setApiCache(): Thiết lập bộ nhớ cache để lưu trữ các kết quả từ các yêu cầu API trước đó.
- setApiRateLimit(): Thiết lập giới hạn tốc độ yêu cầu API trong một khoảng thời gian nhất định.
- setApiRequestHeader(): Thiết lập thông tin header cho yêu cầu API.
- setApiResponseHeader(): Thiết lập thông tin header cho phản hồi từ API.
- setApiLoggingLevel(): Thiết lập mức độ ghi log cho API.
- setApiRetryAttempts(): Thiết lập số lần thử lại khi yêu cầu API thất bại.
- makeApiCall(): Thực hiện một yêu cầu API và trả về kết quả.
- clearApiCache(): Xóa bộ nhớ cache của các kết quả yêu cầu API trước đó.
- getApiRateLimitStatus(): Truy cập trạng thái giới hạn tốc độ hiện tại của yêu cầu API.

Ngoài các phương thức trên, có thể có các phương thức khác phát sinh khi code.
