### ISSUE TITLE
02/04/2023 Xác định các thuộc tính của class UIcomponent

### ISSUE THREAD

**Issue by TrnHunhTnPht** [TrnHunhTnPht/Nhom13-DETAI23-API-DASHBOARD#59]

**Comment by maihaidang2102** [comment]
Xác định các thuộc tính của class UIcomponent : [link](https://docs.google.com/document/d/1Uv2ESbHV_jZL14CJFZHR-2s0AhEgzRXrloxhqtSBhiM/edit?usp=sharing)
DONE TASK 6

**Comment by maihaidang2102** [comment]
Lớp UIComponent đại diện cho các thành phần giao diện người dùng trong hệ thống phần mềm. Các thuộc tính có thể có của lớp UIComponent bao gồm:

- id: Mã định danh duy nhất cho UIComponent.
- type: Loại của UIComponent (ví dụ: button, textbox, checkbox, ...).
- name: Tên gọi của UIComponent.
- position: Vị trí của UIComponent trên giao diện.
- size: Kích thước của UIComponent.
- parent: Thành phần cha của UIComponent trong cây phân cấp các thành phần giao diện.
- isVisible: Cho biết UIComponent có hiển thị trên giao diện hay không.
- isEnabled: Cho biết UIComponent có được bật hoạt động hay không.
- isEditable: Cho biết UIComponent có cho phép người dùng chỉnh sửa nội dung hay không.
- backgroundColor: Màu nền của UIComponent.
- foregroundColor: Màu chữ và hình ảnh của UIComponent.
- borderColor: Màu viền của UIComponent.
- tooltip: Gợi ý hoặc thông tin phụ về UIComponent khi người dùng di chuột qua nó.
- icon: Hình ảnh biểu tượng của UIComponent (nếu có).

Ngoài ra, lớp UIComponent còn có thể bao gồm các thuộc tính khác tùy thuộc vào yêu cầu của hệ thống và tính năng được hỗ trợ.
