### ISSUE TITLE
03/04/2023 Tổng hợp các class lại và vẽ class diagram

### ISSUE THREAD

**Issue by TrnHunhTnPht** [TrnHunhTnPht/Nhom13-DETAI23-API-DASHBOARD#61]
**Tổng hợp các class và vẽ class diagram**
| **Collaborator** | **Assignment** |
|--------|--------|
| @maihaidang2102 | **Task 7** Tổng hợp các class |
| @TrnHunhTnPht | **Task 7** Vẽ class diagram | 
| @vnghia109 | **Task 7** Vẽ class diagram |

**Comment by TrnHunhTnPht** [comment]
[Task 7: Class Diagram](https://drive.google.com/file/d/1LQT5lufjWwyw_93miX50g_Ki-0-D_8yx/view?usp=sharing)

**Comment by maihaidang2102** [comment]
Task7 tuần 3 : Tổng hợp các class [LINK](https://docs.google.com/document/d/1fw8NRu0yfjCiuaBjWAROUHuxDofU9h9gOKRjxVq72Q8/edit?usp=sharing)
DONE TASK 7

**Comment by vnghia109** [comment]
**Task 7 tuần 3:** Vẽ class diagram

[Class Diagram](https://drive.google.com/file/d/1LQT5lufjWwyw_93miX50g_Ki-0-D_8yx/view)
