### ISSUE TITLE
15/03/2023 Tìm hiểu về các Chart phổ biến và chức năng của từng loại

### ISSUE THREAD

**Issue by TrnHunhTnPht** [TrnHunhTnPht/Nhom13-DETAI23-API-DASHBOARD#7]

**Comment by TrnHunhTnPht** [comment]
[Done Task2](https://docs.google.com/document/d/1gL7aWMulTCAcGjU13EU475Z9meAO3Xah29pBDFpcf6U/edit?usp=sharing)

**Comment by maihaidang2102** [comment]
Các chart phổ biến và chức năng [link](https://docs.google.com/document/d/1rHJ6P4tPXq91ALIoucV2dIHV1NyBvtOppX6GLUy9K18/edit?usp=sharing)
